### ISSUE TITLE
v1 crashes after a few hours

### ISSUE THREAD

**Issue by freakshock88** [eelcohn/nRF905-API#14]
Since upgrading to v1, my NodeMCU ESP8266 crashes after running the API for a few hours.
The blue LED also turns off.

I can remove power and restore it, then the NodeMCU boots and the API works again for a few hours.

**Comment by eelcohn** [comment]
Ik heb inmiddels zelf ook het probleem ervaren met mijn setup hier. Ik heb nog geen exact idee waardoor dit wordt veroorzaakt, maar een paar mogelijkheden zijn:
* een watchdog timer die crashte
* een bufferoverflow o.i.d.

Wat kan helpen is om uit te vinden of er ook iets bijzonders te zien is op de seriële poort voordat de boel crasht. Ikzelf heb inmiddels de nRF905 via een USB kabel gekoppeld aan een losse raspberry pi die ik nog had liggen, waar ik nu een seriële monitor op heb draaien.

**Comment by DevSecNinja** [comment]
I have the same issue and I used a serial monitor with HA to get the output of it. Just before it crashed, it returned:
````
fan_main_unit_id=48
````

![image](https://user-images.githubusercontent.com/14926452/100485756-989bae80-3101-11eb-8c58-edc3ee019355.png)

If you want to create the serial monitor sensor as well, attach the USB cable to the Home Assistant host and use the following config (make sure to double check the serial port):

```` yaml
- platform: serial
  serial_port: /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0
  name: "Ventilation-RC Serial"
  baudrate: 115200
````
